#lang pollen

/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on January 18, 2018 */

◊local-require{../utils.rkt}

@font-face {
    font-family: 'charterregular';
    src: url('fonts/bitstream_charter-webfont.eot');
    src: url('fonts/bitstream_charter-webfont.eot?#iefix')         format('embedded-opentype'),
         url('fonts/bitstream_charter-webfont.woff2')              format('woff2'),
         url('fonts/bitstream_charter-webfont.woff')               format('woff'),
         url('fonts/bitstream_charter-webfont.ttf')                format('truetype'),
         url('fonts/bitstream_charter-webfont.svg#charterregular') format('svg');
    font-weight: normal;
    font-style: normal;
}

◊(define body-font-size '(1.2 "em"))
◊(define text-color "#444")

body {
    font-family: 'charterregular';
    max-width: 800px;
    color: ◊|text-color|;

    padding-left: 10px;
    padding-right: 10px;
    padding-bottom: 2em;
    padding-top: 2em;
    margin: auto;

    font-size: ◊(mult-measure 1 body-font-size);
}

a {
   color: ◊|text-color|;
   text-decoration: none;
}

a:hover { background-color: #ffe; }

h1 {
    background: gray;
    color: white;
}

p {
    margin: 0px;
    line-height: ◊(mult-measure 1.15 body-font-size);
}

.CVheader {
    padding-bottom: 1.5em;
    max-width: 600px;
}

.CVname {
    font-size: ◊(mult-measure 1.6 body-font-size);
    margin-bottom: 0.2em;
}

.CVaddress {
    font-size: ◊|body-font-size|em;
    margin-bottom: 0.2em;
}

.CVphone { font-size: ◊(mult-measure 0.9 body-font-size); }

.CVemail { font-size: ◊(mult-measure 0.9 body-font-size); }

.CVsection-title {
    font-size: ◊(mult-measure 0.8 body-font-size);
    margin-bottom: 1em;
}

hr.CVsection-title {
    margin-bottom: 0px;
    margin-top: 1em;
}

.CVobject {
           font-size: ◊(mult-measure 1.08 body-font-size);

           }

.period {
                  display: block;
                  float:right;
                  }

span.tag { width: 20em; }

ul {
    margin-top: 0.5em;
    margin-bottom: 1.5em;
    list-style: none;
}

li::before {
    font-size: ◊(mult-measure 0.6 body-font-size);
   float: left;
    top: 0.5em;
    content: "•";
    display: inline-block;
    width: 1em;
    margin-left: -1em;
    margin-top: 0.3em;
}

li { margin-bottom: 0.5em; }
